FROM alpine

ENTRYPOINT /app/job.sh

LABEL com.ngageoint.seed.manifest="{\"seedVersion\":\"0.0.6\",\"job\":{\"name\":\"random-number-gen\",\"algorithmVersion\":\"0.1.0\",\"packageVersion\":\"0.1.0\",\"title\":\"Random Number Generator\",\"description\":\"Generates a random number and outputs on stdout\",\"authorName\":\"John Doe\",\"timeout\":10,\"interface\":{}}}"
