variables:
  DOCKER_IMAGE: docker:stable
  DIND_IMAGE: docker:dind
  NODE_IMAGE: node

before_script:
  - apk add -U jq bash

validate:
  image: ${NODE_IMAGE}

  script:
  - export SEED_LATEST=$(tail -1 .versions)
  - npm install ajv-cli
  # Use snapshot for remainder for master builds
  - if [[ "${CI_COMMIT_TAG}x" == "x" ]] ; then ./set-version.sh ${SEED_LATEST}-snapshot; ./spec/examples/inject-manifests.sh; fi
  - spec/examples/validate-examples.sh
  cache:
    paths:
      - node_modules

build:
  image: ${DOCKER_IMAGE}

  services:
    - ${DIND_IMAGE}

  script:
  - export SEED_LATEST=$(tail -1 .versions)
  - mkdir -p output
  # Use snapshot for remainder for master builds
  - if [[ "${CI_COMMIT_TAG}x" == "x" ]] ; then ./set-version.sh ${SEED_LATEST}-snapshot; ./spec/examples/inject-manifests.sh; fi
  - spec/generate-outputs.sh
  - git checkout -- spec
  # Build index.adoc WITHOUT snapshot tag
  - if [[ "${CI_COMMIT_TAG}x" == "x" ]] ; then ./set-version.sh ${SEED_LATEST}; spec/examples/inject-manifests.sh; fi
  - spec/add-version-links.sh
  - docker run -v $(pwd)/spec:/documents --rm ${ASCIIDOCTOR_IMAGE} asciidoctor -D /documents/output index.adoc
  - ./spec/collect-versioned-docs.sh
  artifacts:
    paths:
    - spec/output
