= Seed

image:https://badges.gitter.im/ngageoint/seed.svg[link="https://gitter.im/ngageoint/seed?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
image:https://travis-ci.org/ngageoint/seed.svg?branch=master[link="https://travis-ci.org/ngageoint/seed"]

Seed is a general standard to aid in the discovery and consumption of a discrete unit of work contained within a Docker
image.

See the link:http://ngageoint.github.io/seed/[specification] for details.

== Usage

The specification is intended to inform both job and execution framework developers. Detailed examples
are provided for Seed usage in both simple and complex job scenarios and these are recommended for
job developers interested in getting started quickly.

The Seed team is in the process of developing a fully featured CLI that will minimize the domain expertise
required for an job developer to get a Seed image ready for distribution. This will handle the Docker
image construction and publish, so focus can be given to what really matters - describing your job's
purpose, requirements and interface.

== Development

All Seed documentation is made via the excellent AsciiDoc standard. Travis CI is used to compile all the
documentation into html / pdf releases and update the GitHub pages site with all available Seed releases.

Generation of new releases may be done from a clean master branch:

`./generate-release.sh 1.0.0`

This will create a new tag, that will kick off a TravisCI tag build to create release artifacts, update
the master branch with a pointer to that release and finally a TravisCI build of master to update GitHub
pages with the permalink to all available releases.

You can also easily generate release notes and nicely formatted changelog by using the gren CLI:

```
# Assuming gren installed via NPM globally. If not, find here: https://github.com/github-tools/github-release-notes
gren release --override
gren changelog --override
git commit -a -m "Update changelog for release"
git push
```
