The Seed standard is intended to provide a complete definition of the runtime processing, memory and storage
requirements of a discrete unit of work, in addition to the inputs, outputs and potential errors produced.
Completeness is fundamental but the standard accommodates both simple and complex jobs by defining a minimal subset of
REQUIRED properties. The following sections detail every possible REQUIRED and OPTIONAL manifest property in both root
and child objects.

A complete Seed object contained within a `com.ngageoint.seed.manifest` label is always a string-escaped serialized
object. In Seed, an object consists of a collection of name/value pairs -- also called members. For each member, the
name is always a string. Member values are either a string, number, object, array or one of the literals: true, false,
and null. An array consists of elements where each element is a value as described above.

[[seed-section, Seed Object]]
=== Seed Object
The Seed object is the root JSON object that MUST be placed within a `com.ngageoint.seed.manifest` Docker image label.
At a minimum this object MUST define the `seedVersion` and `job` names.

* The Seed object MUST have a member with the name `seedVersion`. The member's value MUST be a string that
conforms to the SemVer standard.
* The Seed object MUST have a member with the name `job`. The member's value MUST be a <<job-section>>.

[source,javascript]
----
{
  "seedVersion": "SEED_VERSION",
  "job": { ... }
}
----

[[job-section, Job Objects]]
==== Job Object
The Job object is the core member for describing a single unit of work and the resources it requires.

* The Job object MUST have a member with the name `name`. The member's value MUST be a string of only lowercase
alpha-numeric, dash or underscore characters (defined by the regex `^[a-z0-9_-]+$`).
* The Job object MUST have a member with the name `algorithmVersion`. The member's value MUST be a string that conforms
to the SemVer standard.
* The Job object MUST have a member with the name `packageVersion`. The member's value MUST be a string that conforms
to the SemVer standard.
* The Job object MUST have a member with the name `title`. The member's value MUST be a string and SHOULD contain a
short descriptive title of the job.
* The Job object MUST have a member with the name `description`. The member's value MUST be a string and SHOULD contain
a full job abstract.
* The Job object MAY have a member with the name `tags`. The member's value MUST be an array of strings and MAY contain
any number of elements.
* The Job object MUST have a member with the name `timeout`. This member's values MUST be a integer indicating a timeout
period measured in seconds. Consuming systems MUST honor this value as a hard limit on job execution time.
* The Job object MUST have a member with the name `maintainer`. The member's value MUST be an object as defined in
<<maintainer-section>>.
* The Job object SHOULD have a member with the name `resources`. This member's value MUST be an object as defined in
<<resources-section>>. It is highly advised that this member be specified, without it resources provided will be default
for the implementing framework.
* The Job object MAY have a member with the name `interface`. This member's value MUST be an object as defined in
<<interface-section>>.
* The Job object MAY have a member with the name `errors`. This member's value MUST be an array containing
elements defined in <<errors-section>>

The following annotated snippet provides quick reference to the use of Job object:

[source,javascript]
----
{
    "name": "my-algorithm", // <1>
    "algorithmVersion": "1.0.0", // <2>
    "packageVersion": "1.0.0", // <3>
    "title": "My first algorithm", // <4>
    "description": "Reads an HDF5 file and outputs two TIFF images, a CSV and manifest containing cell_count", // <5>
    "timeout": 3600,// <6>
    "maintainer": { ... }, // <7>
    "resources": { ... }, // <8>
    "interface": { ... }, // <9>
    "errors": [ ... ] // <10>
}
----
<1> Required string containing job identifier. Limited to regex `^[a-z0-9_-]+$`. `name` and `algorithmVersion` members
combined should be unique system-wide.
<2> Required string containing version identifier of algorithm in SemVer format. `name` and `algorithmVersion` members
combined should be unique system-wide.
<3> Required string containing packaging version identifier in SemVer format. `packageVersion` is used to indicate
updates to the job interface, it should NEVER be used to indicate changes to the algorithm.
<4> Required string containing short job title.
<5> Required string containing job abstract. Inline markup should be avoided, but not prohibited.
<6> Required integer containing job timeout value in seconds.
<7> Required <<maintainer-section>>.
<8> Optional <<resources-section>>.
<9> Optional <<interface-section>>.
<10> Optional array of <<errors-section>>.

[[maintainer-section, Maintainer Object]]
===== Maintainer Object
The Maintainer object is the member that identifies the individual and organization (optional) acting as a point of
contact for a Seed job.

* The Maintainer object MUST have a member with the name `name`. The member's value MUST be a string and SHOULD contain
the full name of maintaining individual.
* The Maintainer object MUST have a member with the name `email`. The member's value MUST be a string and SHOULD contain
the best contact email for maintaining individual or organization.
* The Maintainer object MAY have a member with the name `phone`. The member's value MUST be a string and SHOULD contain
the best contact phone number for maintaining individual or organization.
* The Maintainer object MAY have a member with the name `organization`. The member's value MUST be a string and SHOULD
contain the organization responsible for maintaining or sponsoring Seed job.
* The Maintainer object MAY have a member with the name `url`. The member's value MUST be a string and SHOULD contain a
publicly accessible URL to complete algorithm design or usage documentation.

[source,javascript]
----
{
    "name": "John Doe", // <1>
    "email": "jdoe@example.com", // <2>
    "phone": "666-555-4321", // <3>
    "organization": "E-corp", // <4>
    "url": "http://www.example.com" // <5>
}
----
<1> Required string containing full name of maintaining individual.
<2> Required string containing best contact email for maintaining individual or organization.
<3> Optional string containing best contact phone number for maintaining individual or organization.
<4> Optional string containing organization responsible for maintaining or sponsoring Seed job.
<5> Optional string containing publicly accessible URL to complete algorithm design or usage documentation.

[[resources-section, Resources Object]]
===== Resources Object
The Resources object is the member that identifies all resource requirements for a job. This is most commonly CPU,
memory and disk scalar resources, but MAY in the future accommodate more complex types such as ranges and sets. The
final computed resources allocated for all `scalar` elements MUST be injected as environment variables to the job at run
time. Reference <<environment-variables>> and <<resource-defaults>> for clarification on what the implementing framework
MUST provide.

* The Resources object MUST have a member with the name `scalar`. The member's value is an array of `Scalar`
objects and MAY contain any number of elements. There is no other standard restriction on the array size.

.Scalar Elements
The Scalar objects MAY include any arbitrary custom resource name, but there are reserved resources `cpu`, `disk`,
`mem` and `sharedMem` that have special meaning. The reserved resource names `cpu`, `disk` and `mem` SHOULD be
populated by all Seed compliant images, as the defaults provided at runtime will likely be inadequate to run all but the
most minimal job. The `sharedMem` resource applies primarily to high-performance and scientific applications
and will rarely be needed.

* The Scalar object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) indicating the resource required by the job. Refer to
<<variable-injection>> for details on environment variable available at execution time.
* The Scalar object MUST have a member `value`. The member's value MUST be a number indicating the quantity of the
resource required by the job. When dealing with storage resources such as `mem` or `disk` units of
Mebibytes (MiB) MUST be used.
* The Scalar object MAY have a member `inputMultiplier`. The member's value MUST be a number indicating the factor by
which input file size is multiplied and added to the constant value for resource.

Use of `inputMultiplier` for `mem` or `disk` resource types is useful when memory or output disk requirements of a job
are a function of input file size. The following basic formula computes the resource requirement when an
`inputMultiplier` is defined.

----
resourceRequirement = inputVolume * inputMultiplier + constantValue`
----

For example, when total input file size is 2.0MiB and an `inputMultiplier` of `4.0` and `value` of `0.1` is
specified for `disk`, the following computes the resource requirement:

----
diskRequirement = 2.0MiB * 4.0 + 0.1MiB
----

[source,javascript]
----
[
    { "name": "cpus", "value": 1.0 }, // <1>
    { "name": "disk", "value": 4.0, "inputMultiplier": 4.0 }, // <2>
    { "name": "mem", "value": 64.0, "inputMultiplier": 4.0 }, // <3>
    ... // <4>
]
----
<1> Recommended Scalar element demonstrating single constant scalar value for specifying CPU requirement of job.
<2> Optional Scalar element demonstrating single constant scalar value in addition to a multiplier based on total input
file size for scaling disk requirement of job. This multiplier allows for scaling the output disk space required as a
function of input file size.
<3> Recommended Scalar element demonstrating single constant scalar value in addition to a multiplier based on total
input file size for scaling memory requirement of job.
<4> Optional additional Scalar elements for any custom resources needed by job.

[[interface-section, Interface Object]]
===== Interface Object
The Interface object is the primary member that describes the command arguments, environment variables,
mounts, settings, inputs and outputs defined for a job.

* The Interface object MAY have a member with the name `command`. The member's value MUST be a string specifying the
complete string passed to the container at run time. Based on the Linux shell, shell escaping of special characters
MAY be required. If a Docker ENTRYPOINT is defined that launches the executable, omission of the executable MAY be
necessary in `command` string. The Seed `command` member can be treated as analogous to the Docker CMD statement.
* The Interface object MAY have a member with the name `inputs`. This member's value MUST be an object as defined in
<<inputs-section>>.
* The Interface object MAY have a member with the name `outputs`. This member's value MUST be an object as defined in
<<outputs-section>>.
* The Interface object MAY have a member with the name `mounts`. The member's value MUST be an array of `Mounts`
objects (see <<mounts-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.
* The Interface object MAY have a member with the name `settings`. The member's value MUST be an array of `Settings`
objects (see <<settings-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.

The following annotated snippet provides quick reference to the use of Interface object:

[source,javascript]
----
{
    "command": "/app/job.sh ${INPUT_FILE} ${OUTPUT_DIR}", // <1>
    "inputs": { "files": [ { "name": "INPUT_FILE", ... }, ... ] }, // <2>
    "outputs": { ... }, // <3>
    "mounts": [ ... ], // <4>
    "settings": [ ... ] // <5>
}
----
<1> Optional string indicating the job arguments. Reference <<environment-variables>> for clarification on what the
implementing framework MUST provide. Linux shell escaping MAY be needed in the case of special characters.
<2> Optional <<inputs-section>>. This is the means to inject external data into the job container.
<3> Optional <<outputs-section>>. This is the means to capture results from the job container.
<4> Optional <<mounts-section>>. This defines any directories that need to be mounted into the job container.
<5> Optional <<settings-section>>. This defines any environment specific settings needed at run time.

[[inputs-section, Inputs Object]]
====== Inputs Object
The Inputs object is the member responsible for indicating immutable input data available to the Seed image at
runtime.

* The Inputs object MAY have a member `files`. The member's value MUST be an array of objects defined in the Files 
Elements sub-section.
* The Inputs object MAY have a member `json`. The member's value MUST be an array of objects defined in the JSON 
Elements sub-section.

.Files Elements

Critical implementation details related to `multiple` member should be referenced in
<<environment-variables,environment variables>>.

* The Files object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) indicating the environment variable name that will be
injected by the processing platform for job consumption. Refer to <<variable-injection>> for details on environment
variable available at execution time.
* The Files object MUST have a member `mediaType`. The member's value MUST be an array of strings that MUST indicate 
the IANA Media types that the job accepts.
* The Files object MAY have a member `multiple`. The member's value MUST be a boolean indicating whether multiple
physical files are processed by this `Files` element. If omitted, the default value MUST be treated as false. If true,
the `command` placeholder will be replaced with an absolute directory containing all files. If false or omitted, the
`command` placeholder will be replaced with an absolute path to a single file.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) indicating the environment variable name that will be
injected by the processing platform for job consumption. Refer to <<variable-injection>> for details on environment
variable available at execution time.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate a valid JSON schema type.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippet provides quick reference to the use of Inputs object:

[source,javascript]
----
{
    "files": [ // <1>
        {
            "name": "INPUT_FILE", // <2>
            "mediaType": [ "image/x-hdf5-image" ], // <3>
            "multiple": false, // <4>
            "required": true // <5>
        },
        ...
    ]
    "json": [ // <6>
        {
            "name": "INPUT_STRING",<7>
            "type": "string", // <8>
            "required": false // <9>
        }
    ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing name used to inject data via environment variables.
<3> Required array containing a list of accepted Media types.
<4> Optional boolean indicating whether this element represents multiple files (flat directory) vs one file (false).
Default is `false`.
<5> Optional boolean indicating whether job requires this particular file. Default is `true`.
<6> Optional array containing elements defined by JSON Elements sub-section.
<7> Required string containing name used to inject data via environment variables.
<8> Required string containing a valid JSON schema type for input validation.
<9> Optional boolean indicating whether job requires this particular JSON input. Default is `true`.

[[outputs-section, Outputs Object]]
====== Outputs Object
The Outputs object is the member responsible for indicating all output data and the means to capture that data
following the execution of a Seed image. Data can be captured in two different forms: directly as a file or
extracted JSON from a manifest. File type output is simply matched based on a standard glob pattern. JSON objects are
expected to be gathered from a JSON manifest that by Seed standard convention MUST be written at the root of the job
output directory as `seed.output.manifest.json`. The absolute path to the job output directory is REQUIRED to be passed
into the container at job execution time in the `OUTPUT_DIR` environment variable. Special attention should be given to
<<output-data-permissions,output file permissions>> and support is provided for defining
<<extended-file-metadata,extended metadata>>.

* The Outputs object MAY have a member `files`. The member's value MUST be an array of objects defined in the Files 
Elements sub-section.
* The Outputs object MAY have a member `json`. The member's value MUST be an array of objects defined in the JSON 
Elements sub-section.

.Files Elements
* The Files object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or underscore
characters (defined by the regex `^[a-zA-Z_-]+$`) indicating the key the processing system will place the file name
captured for downstream processing.
* The Files object MUST have a member `mediaType`. The member's value MUST indicate the IANA Media type for
the file being captured by Outputs.
* The Files object MUST have a member `pattern`. The member's value MUST indicate a standard glob pattern for the
capture of files.
* The Files object MAY have a member `count`. The member's value MUST be a string that accepts 2 possibilities:
positive numeric values or a `\*`. Numeric values indicate an explicit match expected for `pattern` while `*` indicates
matching with no upper bound.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value is `true`.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) indicating the key the processing system will place the
JSON member value in for downstream use. When `key` member is omitted, it must be a case-sensitive match of the member
key in result manifest.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate the JSON schema type of
the member being captured from the result manifest.
* The JSON object MAY have a member `key`. The member's value MUST be a string and indicate the case-sensitive result
manifest member to capture. If omitted, the result member key is assumed to be a case-sensitive match for the above
defined `name` member.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippets provides quick reference to the use of Outputs object:

[source,javascript]
.Result Manifest
----
{
    "cellCount": 256,
    ...
}
----

[source,javascript]
.Seed Manifest - Outputs object
----
"outputs": {
    "files": [ // <1>
        {
            "name": "OUTPUT_TIFFS", // <2>
            "mediaType": "image/tiff", // <3>
            "pattern": "outfile*.tif", // <4>
            "count": "2", // <5>
            "required": true // <6>
        },
        ...
    ],
    "json": [ // <7>
        {
            "name": "CELL_COUNT", // <8>
            "type": "integer", // <9>
            "key": "cellCount" // <10>
        },
        ...
    ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing output identifier.
<3> Required string containing IANA Media type of file.
<4> Required string containing glob expression for file capture. Processing system is expected to
capture output relative to OUTPUT_DIR.
<5> Optional string containing either a numeric count or `*` for unbounded output. Default value
is `1`.
<6> Optional boolean indicating whether processing system should assume failure if output data is missing. Default value
is true.
<7> Optional array containing elements defined by JSON Elements sub-section.
<8> Required string containing output identifier. MUST be used by processing framework to match member for capture from
result manifest in absence of `key` member.
<9> Required string containing JSON schema type of member extracted from result manifest.
<10> Optional string containing key of result manifest member for extraction. This allows mapping from a result manifest
member key that differs from the value of `name` member.

[[mounts-section, Mounts Object]]
====== Mounts Object
The Mounts object is the member responsible for indicating any additional directories that must be mounted into the
container for the Job to run. A mount directory is typically a shared file system directory that contains some set of
reference data that the Job requires.

* The Mounts object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) that correlates mount references elsewhere in the Interface
to an external mount configuration that specifies how the mount is provided.
* The Mounts object MUST have a member `path`. The member's value MUST be an absolute file system path specifying where in
 the container the Job expects the shared directory to be mounted.
* The Settings object MAY have a member `mode`. The member's value MUST be a string that either specifies "ro" for read-only
 access to the directory or "rw" for read-write access. Default value is "ro".

The following annotated snippet provides quick reference to the use of the Mounts object:

[source,javascript]
----
[
    {
        "name": "MOUNT1", // <1>
        "path": "/the/container/path", // <2>
        "mode": "ro" // <3>
    },
    ...
]
----
<1> Required string containing the name to be used to lookup uses in the Interface.
<2> Required string indicating the absolute file system path where the directory should be mounted.
<3> Optional string indicating whether the directory should be mounted in read-only ("ro") or read-write ("rw") mode.

[[settings-section, Settings Object]]
====== Settings Object
The Settings object is the member responsible for indicating all content not related to data that is needed for the
Seed job to run. These will be exposed as environment variables at run time. Most commonly, Settings will be used for
environment specific configuration or external credentials.

While it is _highly_ advised that Seed jobs SHOULD limit input / output to the provided constructs (`inputs` /
`outputs`), there are justified use cases for violating this encapsulation. If database ingestion or downstream
 messaging are necessary, this is a reasonable mechanism to accomplish that.

* The Settings object MUST have a member `name`. The member's value MUST be a string of only alphabetic, dash or
underscore characters (defined by the regex `^[a-zA-Z_-]+$`) that indicates the environment variable to be injected at
run time. Refer to <<variable-injection>> for details on environment variable available at execution time.
* The Settings object MAY have a member `secret`. The member's value MUST be a boolean that indicates whether the value
 associated with the named setting is secret and stored as a secure string.

The following annotated snippet provides quick reference to the use of the Settings object:

[source,javascript]
----
[
    {
        "name": "SETTING1", // <1>
        "secret": true // <2>
    },
    ...
]
----
<1> Required string containing the environment variable name to be injected at run time.
<2> Optional boolean indicating whether the setting value is sensitive and stored as a secret.

[[errors-section, Errors Objects]]
===== Errors Object
The Errors object allows for _developers_ to map arbitrary exit codes to meaningful textual descriptions. This is useful
in passing information to the _executor_ to differentiate between data and algorithm errors.

* The Errors object MUST have a member `code`. The member's value MUST be an integer indicating the exit code of
the executing job process.
* The Errors object MUST have a member `title`. The member's value MUST be a string indicating the short
descriptive title of the error.
* The Errors object MAY have a member `description`. The member's value MUST be a string indicating the complete
error description and possible causes.
* The Errors object MAY have a member `category`. The member's value MUST be a string containing one of the following 
values: `algorithm`, `data` or `system`. If omitted, the default value is `algorithm`.

The following annotated snippet provides quick reference to the use of Errors objects:

[source,javascript]
----
[
    {
        "code": 1, // <1>
        "title": "Error Name", // <2>
        "description": "Error Description", // <3>
        "category": "system" // <4>
    },
    ...
]
----
<1> Required integer indicating job process exit code.
<2> Required string containing human-friendly short name of error.
<3> Optional string containing complete error code description.
<4> Optional string containing the error type. This value MUST be either: `algorithm`, `data` or `system`. The default
value is `algorithm`.
