The Seed standard is intended to provide a complete definition of the runtime processing, memory and storage
requirements of a discrete unit of work, in addition to the inputs, outputs and potential errors produced.
Completeness is fundamental but the standard accommodates both simple and complex jobs by defining a minimal subset of
REQUIRED properties. The following sections detail every possible REQUIRED and OPTIONAL manifest property in both root
and child objects.

A complete Seed object contained within a `com.ngageoint.seed.manifest` label is always a string-escaped serialized
object. In Seed, an object consists of a collection of name/value pairs -- also called members. For each member, the
name is always a string. Member values are either a string, number, object, array or one of the literals: true, false,
and null. An array consists of elements where each element is a value as described above.

[[seed-section, Seed Object]]
=== Seed Object
The Seed object is the root JSON object that MUST be placed within a `com.ngageoint.seed.manifest` Docker image label.
At a minimum this object MUST define the `seedVersion` and `job` names.

*seedVersion* ::
    Required; MUST be a string that conforms to the SemVer standard.
*job* ::
    Required; MUST be a <<job-section>>.

*EXAMPLE* +
[source,javascript]
----
{
  "seedVersion": "SEED_VERSION",
  "job": { ... },
}
----

[[job-section, Job Object]]
==== Job Object
The Job object is the core member for describing a single unit of work and the resources it requires.

*name* ::
    Required string containing job identifier. MUST be a string of only alphanumeric or dash characters (defined by the regex† `^[a-zA-Z0-9-]+$`). `name` and `jobVersion` members combined should be unique system-wide.
*jobVersion* ::
    Required string containing version identifier of job in SemVer format. `name` and `jobVersion` members combined should be unique system-wide.
*packageVersion* ::
    Required string containing packaging version identifier in SemVer format. `packageVersion` is used to indicate updates to the job interface, it should NEVER be used to indicate changes to the job.
*title* ::
    Required string that should contain a short descriptive title of the job.
*description* ::
    Required string containing a full job abstract. Inline markup should be avoided, but is not prohibited.
*tags* ::
    Optional array of strings and may contain any number of elements.
*timeout* ::
    Required integer indicating a job timeout period measured in seconds. Consuming systems MUST honor this value as a hard limit on job execution time.
*maintainer* ::
    Required object as defined in <<maintainer-section>>.
*resources* ::
    Optional object as defined in <<resources-section>>. It is highly advised that this member be specified; Without it resources provided will be default for the implementing framework.
*interface* ::
    Optional object as defined in <<interface-section>>.
*errors* ::
    Optional array containing elements defined in <<errors-section>>.

*EXAMPLE* +
[source,javascript]
----
{
    "name": "my-job", 
    "jobVersion": "1.0.0",
    "packageVersion": "1.0.0",
    "title": "My first job",
    "description": "Reads an HDF5 file and outputs two TIFF images, a CSV and manifest containing cell_count",
    "tags": [ ... ],
    "timeout": 3600, 
    "maintainer": { ... },
    "resources": { ... },
    "interface": { ... },
    "errors": [ ... ]
}
----

[[maintainer-section, Maintainer Object]]
===== Maintainer Object
The Maintainer object is the member that identifies the individual and organization (optional) acting as a point of
contact for a Seed job.

*name* ::
    Required string containing the full name of maintaining individual.
*email* ::
    Required string containing the best contact email for maintaining individual or organization.
*phone* ::
    Optional string containing best contact phone number for maintaining individual or organization.
*organization* ::
    Optional string containing the organization responsible for maintaining or sponsoring the Seed job.
*url* ::
    Optional string containing a publicly accessible URL to complete job design or usage documentation.

*EXAMPLE* +
[source,javascript]
----
{
    "name": "John Doe",
    "email": "jdoe@example.com",
    "phone": "666-555-4321",
    "organization": "E-corp",
    "url": "http://www.example.com"
}
----

[[resources-section, Resources Object]]
===== Resources Object
The Resources object is the member that identifies all resource requirements for a job. This is most commonly CPU,
memory and disk scalar resources, but MAY in the future accommodate more complex types such as ranges and sets. The
final computed resources allocated for all `scalar` elements MUST be injected as environment variables to the job at run
time. Reference <<environment-variables>> and <<resource-defaults>> for clarification on what the implementing framework
MUST provide.

The Scalar object is required and MUST be an array of <<.Scalar Object>>s that MAY contain any number of elements. There 
is no other standard restriction on the array size.

.Scalar Object
The Scalar objects MAY include any arbitrary custom resource name, but there are reserved resources `cpus`, `disk`,
`mem` and `sharedMem` that have special meaning. The reserved resource names `cpus`, `disk` and `mem` SHOULD be
populated by all Seed compliant images, as the defaults provided at runtime will likely be inadequate to run all but the
most minimal job. The `sharedMem` resource applies primarily to high-performance and scientific applications
and will rarely be needed.

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) indicating the resource required by the job. Refer to <<variable-injection>> for details on environment variable available at execution time.

*value* ::
    Required; MUST be a number indicating the quantity of the resource required by the job. When dealing with storage resources such as `mem` or `disk` units of Mebibytes (MiB) MUST be used.

*inputMultiplier* :: 
    Optional number indicating the factor by which input file size is multiplied and added to the constant value for resource.

*NOTE*: Use of `inputMultiplier` for `mem` or `disk` resource types is useful when memory or output disk requirements of a job are a function of input file size. The following basic formula computes the resource requirement when an `inputMultiplier` is defined.

----
resourceRequirement = inputVolume * inputMultiplier + constantValue
----

For example, when total input file size is 2.0MiB and an `inputMultiplier` of `4.0` and `value` of `0.1` is
specified for `disk`, the following computes the resource requirement:

----
diskRequirement = 2.0MiB * 4.0 + 0.1MiB
----

_The following annotated snippet provides quick reference to the use of Scalar object:_ +
[source,javascript]
----
[
    { "name": "cpus", "value": 1.0 }, // <1>
    { "name": "disk", "value": 4.0, "inputMultiplier": 4.0 }, // <2>
    { "name": "mem", "value": 64.0, "inputMultiplier": 4.0 }, // <3>
    ... // <4>
]
----

<1> Recommended Scalar object demonstrating single constant scalar value for specifying CPU requirement of job.
<2> Optional Scalar object demonstrating single constant scalar value in addition to a multiplier based on total input file size for scaling disk requirement of job. This multiplier allows for scaling the output disk space required as a function of input file size.
<3> Recommended Scalar object demonstrating single constant scalar value in addition to a multiplier based on total input file size for scaling memory requirement of job.
<4> Optional additional Scalar objects for any custom resources needed by job.

[[interface-section, Interface Object]]
===== Interface Object
The Interface object is the primary member that describes the command arguments, environment variables, mounts, settings, inputs and outputs defined for a job.

*command* ::
    Optional string specifying the complete string, including job arguments, passed to the container at run time. Based on the Linux shell, shell escaping of special characters MAY be required. If a Docker ENTRYPOINT is defined that launches the executable, omission of the executable MAY be necessary in `command` string. The Seed `command` member can be treated as analogous to the Docker CMD statement. Reference <<environment-variables>> for clarification on what the implementing framework MUST provide. 
*inputs* :: 
    Optional object as defined in <<inputs-section>> as a means to inject external data into the job container.
*outputs* ::
    Optional object as defined in <<outputs-section>> as the means to capture results from the job container.
*mounts* ::
    Optional array of `Mounts` objects (see <<mounts-section>>) that defines any directories that need to be mounted into the job container. MUST be an array and MAY contain any number of elements. There is no other standard restriction on the array size. 
*settings* :: 
    Optional array of `Settings` objects (see <<settings-section>>) that defines any environment specific settings needed at run time. MUST be an array and MAY contain any number of elements. There is no other standard restriction on the array size. 

*EXAMPLE:* +
[source,javascript]
----
{
    "command": "/app/job.sh ${INPUT_FILE} ${OUTPUT_DIR}",
    "inputs": { "files": [ { "name": "INPUT_FILE", ... }, ... ] },
    "outputs": { ... },
    "mounts": [ ... ],
    "settings": [ ... ]
}
----

[[inputs-section, Inputs Object]]
====== Inputs Object
The Inputs object is the member responsible for indicating immutable input data available to the Seed image at runtime.

*files* ::
    Optional array of objects defined in the <<.Files Object>> sub-section.

*json* ::
    Optional array of objects defined in the <<.JSON Object>> sub-section.

.Files Object

Critical implementation details related to `multiple` member should be referenced in<<environment-variables,environment variables>>. The following description defines the `files` object members.

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) indicating the unique name to use for referring to this input. All inputs will be passed as environment variables, with the environment variable names based upon the input names. Refer to <<variable-injection>> for details on environment variables available at execution time.

*mediaTypes* ::
    Optional array of strings that MUST indicate the IANA Media types that the job accepts. An executor† MAY use any provided media types to report validation warnings to the user in the case of mismatched types.

*multiple* ::
    Optional boolean indicating whether multiple physical files are processed by this `Files` element. If omitted, the default value MUST be treated as false. If true, the value injected into the `command` placeholder will be an absolute directory containing all files for this input. If false (or omitted), the value injected into the `command` placeholder will be an absolute path to a single file.

*partial* ::
    Optional boolean indicating whether input file is required in whole or in part. This allows an executor† to make intelligent choices when providing very large files to a job. This should only be set to true if the job is expected to use less than half of very large input files. If omitted, the default value MUST be treated as false.

*required* ::
    Optional boolean indicating whether this input value SHOULD always be expected. If omitted, the default value MUST be treated as true.

.JSON Object
The following description defines the `json` object members.

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) indicating the unique name to use for referring to this input. All inputs will be passed as environment variables, with the environment variable names based upon the input names. Refer to <<variable-injection>> for details on environment variables available at execution time.

*type* ::
    Required string that indicates a valid JSON schema type.

*required* ::
    Optional boolean indicating whether this input value SHOULD always be expected. If omitted, the default value MUST be treated as true.

*EXAMPLE:* +
[source,javascript]
----
{
    "files": [ 
        {
            "name": "INPUT_FILE", 
            "mediaTypes": [ "image/x-hdf5-image" ],
            "multiple": false,
            "partial": true,
            "required": true
        },
        ...
    ]
    "json": [
        {
            "name": "INPUT_STRING",
            "type": "string",
            "required": false
        }
    ]
}
----

[[outputs-section, Outputs Object]]
====== Outputs Object
The Outputs object is the member responsible for indicating all output data and the means to capture that data
following the execution of a Seed image. Data can be captured in two different forms: directly as a file or
extracted JSON from a manifest. File type output is simply matched based on a standard glob pattern. Recursively scanning
directories is NOT supported, but a known subdirectory structure will work (e.g. base/sub-*/*.ext).  JSON objects are
expected to be gathered from a JSON manifest that by Seed standard convention MUST be written at the root of the job
output directory as `seed.outputs.json`. The absolute path to the job output directory is REQUIRED to be passed
into the container at job execution time in the `OUTPUT_DIR` environment variable. Special attention should be given to
<<output-data-capture,output file permissions>> and support is provided for defining
<<extended-file-metadata,extended metadata>>.

*files* ::
    Optional array containing elements defined in the Files Object sub-section.

*json* ::
    Optional array containing elements defined in the JSON Object sub-section.

.Files Object

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) indicating the unique name to use for referring to this output.
*mediaType* ::
    Optional string indicating the IANA Media type for the file being captured by Outputs.
*pattern* ::
    Required string indicating a standard glob pattern for the capture of files. Executor† is expected to capture output relative to OUTPUT_DIR.
*multiple* ::
    Optional boolean indicating whether single or multiple output files may be captured by this `Files` element. If omitted, the default value MUST be treated as false.
*required* ::
    Optional boolean indicating whether this input value SHOULD always be expected and if the executor† should assume failure if output data is missing. If omitted, the default value is `true`.

.JSON Object

*name* ::
    Required; MUST be a string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) indicating the unique name to use for referring to this output. When `key` member is omitted, it must be a case-sensitive match of the member key in `seed.outputs.json` file.
*type* ::
    Required string indicating the JSON schema type of the member being captured from the `seed.outputs.json` file.
*key* ::
    Optional string indicating the case-sensitive `seed.outputs.json` member to capture. If omitted, the member key is assumed to be a case-sensitive match for the above defined `name` member.
*required* ::
    Optional boolean indicating whether this input value SHOULD always be expected. If omitted, the default value MUST be treated as true.

*EXAMPLE*: +
[source,javascript]
----
{
    "files": [
        {
            "name": "OUTPUT_TIFFS",
            "mediaType": "image/tiff",
            "pattern": "outfile*.tif",
            "multiple": false,
            "required": true
        },
        ...
    ],
    "json": [
        {
            "name": "CELL_COUNT",
            "type": "integer",
            "key": "cellCount"
        },
        ...
    ]
}
----

Resulting seed.outputs.json: +
[source,javascript]
----
{
    "cellCount": 256,
    ...
}
----

[[mounts-section, Mounts Object]]
====== Mounts Object
The Mounts object is the member responsible for indicating any additional directories that must be mounted into the
container for the Job to run. A mount directory is typically a shared file system directory that contains some set of
reference data that the Job requires.

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) that correlates mount references elsewhere in the Interface to an external mount configuration that specifies how the mount is provided.
*path* ::
    Required string indicating an absolute file system path specifying where in the container the Job expects the shared directory to be mounted.
*mode* ::
    Optional string that either specifies "ro" for read-only access to the directory or "rw" for read-write access. Default value is "ro".

*EXAMPLE* +
[source,javascript]
----
[
    {
        "name": "MOUNT1", 
        "path": "/the/container/path",
        "mode": "ro"
    },
    ...
]
----

[[settings-section, Settings Object]]
====== Settings Object
The Settings object is the member responsible for indicating all content not related to data that is needed for the
Seed job to run. These will be exposed as environment variables at run time. Most commonly, Settings will be used for
environment specific configuration or external credentials.

While it is _highly_ advised that Seed jobs SHOULD limit input / output to the provided constructs (`inputs` /
`outputs`), there are justified use cases for violating this encapsulation. If database ingestion or downstream
 messaging are necessary, this is a reasonable mechanism to accomplish that.

*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z0-9_-]+$`) that indicates the environment variable to be injected at run time. Refer to <<variable-injection>> for details on environment variable available at execution time.
*secret* ::
    Optional boolean that indicates whether the value associated with the named setting is secret and stored as a secure string.

*EXAMPLE:* +
[source,javascript]
----
[
   {
       "name": "SETTING1",
       "secret": true
   },
   ...
]
----

[[errors-section, Errors Objects]]
===== Errors Object
The Errors object allows for developers† to map arbitrary exit codes to meaningful textual descriptions. This is useful
in passing information to the executor† to differentiate between data and job errors.

*code* ::
    Required integer indicating the exit code of the executing job process.
*name* ::
    Required string of only alphanumeric, dash or underscore characters (defined by the regex† `^[a-zA-Z_-]+$`) indicating the unique name to use for referring to this error. An executor† MAY use member for correlation of error codes across job versions.
*title* ::
    Required string indicating the human-friendly, short descriptive title of the error.
*description* ::
    Optional string indicating the complete error code description and possible causes.
*category* ::
    Optional string containing one of the following values: `job` or `data`. If omitted, the default value is `job`.

*EXAMPLE:* +
[source,javascript]
----
[
    {
        "code": 1, 
        "title": "Error Name",
        "description": "Error Description",
        "category": "job"
    },
    ...
]
----
