The Seed standard is intended to provide a complete definition of the runtime processing, memory and storage
requirements of a discrete unit of work, in addition to the inputs, outputs and potential errors produced.
Completeness is fundamental but the standard accommodates both simple and complex jobs by defining a minimal subset of
REQUIRED properties. The following sections detail every possible REQUIRED and OPTIONAL manifest property in both root
and child objects.

A complete Seed object contained within a com.ngageoint.seed.manifest label is always a string-escaped serialized
object. In Seed, an object consists of a collection of name/value pairs -- also called members. For each member, the
name is always a string. Member values are either a string, number, object, array or one of the literals: true, false,
and null. An array consists of elements where each element is a value as described above.

[[seed-section, Seed Object]]
=== Seed Object
The Seed object is the root JSON object that MUST be placed within a com.ngageoint.seed.manifest Docker image label.
At a minimum this object MUST define the `seedVersion` and `job` names.

* The Seed object MUST have a member with the name `seedVersion`. The member's value MUST be a string that
conforms to the SemVer standard.
* The Seed object MUST have a member with the name `job`. The member's value is a `Job` object.

[source,javascript]
----
{
  "seedVersion": "SEED_VERSION",
  "job": { ... }
}
----

[[job-section, Job Objects]]
==== Job Object
The Job object is the core member for describing a single unit of work and the resources it requires.

* The Job object MUST have a member with the name `name`. The member's value MUST be a string of only lowercase
alpha-numeric, dash or underscore characters (defined by the regex `[a-z0-9_-]+`).
* The Job object MUST have a member with the name `algorithmVersion`. The member's value MUST be a string that conforms
to the SemVer standard.
* The Job object MUST have a member with the name `packageVersion`. The member's value MUST be a string that conforms
to the SemVer standard.
* The Job object MUST have a member with the name `title`. The member's value MUST be a string and SHOULD contain a
short descriptive title of the job.
* The Job object MUST have a member with the name `description`. The member's value MUST be a string and SHOULD contain
a full job abstract.
* The Job object MAY have a member with the name `tag`. The member's value MUST be an array of strings and MAY contain
any number of elements.
* The Job object MUST have a member with the name `authorName`. The member's value MUST be a string and SHOULD contain
the authoring individual or organization.
* The Job object MAY have a member with the name `authorEmail`. The member's value MUST be a string and SHOULD contain
the authoring email address.
* The Job object MAY have a member with the name `authorUrl`. The member's value MUST be a string and SHOULD contain a
publicly accessible URL with further job detail.
* The Job object MUST have a member with the name `timeout`. This member's values MUST be a integer indicating a timeout
period measured in seconds. Consuming systems MUST honor this value as a hard limit on job execution time.
* The Job object MUST have a member with the name `cpus`. This member's value MUST be a number indicating the whole or
fractional CPUs allocated for the job.
* The Job object MUST have a member with the name `mem`. This member's value MUST be a number indicating the memory
requirement in Mebibytes (MiB) for the job. Fractional MiB values MAY be used to indicate allocations below 1 MiB.
* The Job object MAY have a member with the name `sharedMem`. This member's value MUST be a number indicating the
shared memory (/dev/shm) requirement in Mebibytes (MiB) for the job. Fractional MiB values MAY be used to indicate
allocations below 1 MiB. If omitted, the default of 0.0 may be assumed.
* The Job object MAY have a member with the name `storage`. This member's value MUST be a number indicating the runtime
ephemeral storage requirements in Mebibytes (MiB) of the job. If omitted, the default of 0.0 may be assumed.
* The Job object MUST have a member with the name `interface`. This member's value MUST be an object as defined in
<<interface-section>>.
* The Job object MAY have a member with the name `errorMapping`. This member's value MUST be an array containing
elements defined in <<errormapping-section>>

The following annotated snippet provides quick reference to the use of Job object:

[source,javascript]
----
{
    "name": "my-algorithm", // <1>
    "algorithmVersion": "1.0.0", // <2>
    "packageVersion": "1.0.0", // <3>
    "title": "My first algorithm", // <4>
    "description": "Reads an HDF5 file and outputs two TIFF images, a CSV and manifest containing cell_count", // <5>
    "authorName": "John Doe", // <6>
    "authorEmail": "jdoe@example.com", <7>
    "authorUrl": "http://www.example.com", // <8>
    "timeout": 3600,// <9>
    "cpus": 10.0, // <10>
    "mem": 10240.0, // <11>
    "sharedMem": 0.0, // <12>
    "storage": 0.0, // <13>
    "interface": { ... }, // <14>
    "errorMapping": [ ... ] // <15>
}
----
<1> Required string containing job identifier. Limited to regex `[a-z0-9_-]+`. `name` and `algorithmVersion` members
combined should be unique system-wide.
<2> Required string containing version identifier of algorithm in SemVer format. `name` and `algorithmVersion` members
combined should be unique system-wide.
<3> Required string containing packaging version identifier in SemVer format. `packageVersion` is used to indicate
updates to the job interface, it should NEVER be used to indicate changes to the algorithm.
<4> Required string containing short job title.
<5> Required string containing job abstract. Inline markup should be avoided, but not prohibited.
<6> Required string containing job author name or organization.
<7> Optional string containing job author email.
<8> Optional string containing URL to job website.
<9> Required integer containing job timeout value in seconds.
<10> Required number containing CPU needs of job. Whole or fractional values allowed.
<11> Required number containing memory needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<12> Optional number containing shared memory needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<13> Optional number containing storage needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<14> Required <<interface-section>>.
<15> Optional array of <<errormapping-section>>.

[[interface-section, Interface Object]]
===== Interface Object
The Interface object is the primary member that describes the command arguments, environment variables,
mounts, settings, inputs and outputs defined for a job.

* The Interface object MAY have a member with the name `cmd`. The member's value MUST be a string specifying the
complete string passed to the container at run time. Based on the Linux shell, shell escaping of special characters
MAY be required. If a Docker ENTRYPOINT is defined that launches the executable, omission of the executable MAY be
necessary in `cmd` string. The Seed `cmd` member can be treated as analogous to the Docker CMD statement.
* The Interface object MAY have a member with the name `inputData`. This member's value MUST be an object as defined in
<<inputdata-section>>.
* The Interface object MAY have a member with the name `outputData`. This member's value MUST be an object as defined in
<<outputdata-section>>.
* The Interface object MAY have a member with the name `mounts`. The member's value is an array of `Mounts`
objects (see <<mounts-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.
* The Interface object MAY have a member with the name `settings`. The member's value is an array of `Settings`
objects (see <<settings-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.

The following annotated snippet provides quick reference to the use of Interface object:

[source,javascript]
----
{
    "cmd": "/app/job.sh ${INPUT_FILE} ${JOB_OUTPUT_DIR}", // <1>
    "inputData": { "files": [ { "name": "INPUT_FILE", ... }, ... ] }, // <2>
    "outputData": { ... }, // <3>
    "mounts": [ ... ], // <4>
    "settings": [ ... ] // <5>
}
----
<1> Optional string indicating the job arguments. Reference <<environment-variables>> for clarification on what the
implementing framework MUST provide. Linux shell escaping MAY be needed in the case of special characters.
<2> Optional <<inputdata-section>>. This is the means to inject external data into the job container.
<3> Optional <<outputdata-section>>. This is the means to capture results from the job container.
<4> Optional <<mounts-section>>. This defines any directories that need to be mounted into the job container.
<5> Optional <<settings-section>>. This defines any environment specific settings needed at run time.

[[inputdata-section, InputData Object]]
====== InputData Object
The InputData object is the member responsible for indicating all mutable content available to the Seed image at
runtime.

* The InputData object MAY have a member `files`. The member's value is an array of objects defined in Files Elements
sub-section.
* The InputData object MAY have a member `json`. The member's value is an array of objects defined in JSON Elements
sub-section.

.Files Elements
* The Files object MUST have a member `name`. The member's value MUST be a string indicating the environment
variable name that will be injected by the processing platform for job consumption.
* The Files object MUST have a member `mediaType`. The member's value MUST indicate the IANA Media type for
the file being captured by OutputData.
* The Files object MAY have a member `multiple`. The member's value MUST be a boolean indicating whether this input
value is one or multiple files. If true, the args placeholder will be replaced with an absolute directory containing all files.
If false or omitted, the args placeholder will be replaced with an absolute path to a single file.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string indicating the environment
variable name that will be injected by the processing platform for job consumption.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate a valid JSON schema type.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippet provides quick reference to the use of InputData object:

[source,javascript]
----
{
    "files": [ // <1>
        {
            "name": "INPUT_FILE", // <2>
            "mediaType": [ "image/x-hdf5-image" ], // <3>
            "multiple": false // <4>
            "required": true // <5>
        },
        ...
    ]
    "json": [ // <6>
        {
            "name": "INPUT_STRING",<7>
            "type": "string", // <8>
            "required": false // <9>
        }
    ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing name used to inject data via environment variables.
<3> Required array containing a list of accepted Media types.
<4> Optional boolean indicating whether this element represents multiple files (flat directory) vs one file (false). Default is `false`.
<5> Optional boolean indicating whether job requires this particular file. Default is `true`.
<6> Optional array containing elements defined by JSON Elements sub-section.
<7> Required string containing name used to inject data via environment variables.
<8> Required string containing a valid JSON schema type for input validation.
<9> Optional boolean indicating whether job requires this particular JSON input. Default is `true`.

[[outputdata-section, OutputData Object]]
====== OutputData Object
The OutputData object is the member responsible for indicating all output data and the means to capture that data
following the execution of a Seed image. Data can be captured in two different forms: directly as a file or
extracted JSON from a manifest. File type output is simply matched based on a standard glob pattern. JSON objects are
expected to be gathered from a JSON manifest that by Seed standard convention MUST be written at the root of the job
output directory as `results_manifest.json`. The absolute path to the job output directory is REQUIRED to be passed into
the container at job execution time in the `JOB_OUTPUT_DIR` environment variable. Special attention should be given to
<<output-data-permissions,output file permissions>> and support is provided for defining
<<extended-file-metadata,extended metadata>>.

* The OutputData object MAY have a member `files`. The member's value is an array of objects defined in Files Elements
sub-section.
* The OutputData object MAY have a member `json`. The member's value is an array of objects defined in JSON Elements
sub-section.

.Files Elements
* The Files object MUST have a member `name`. The member's value MUST be a string indicating the key the processing
system will place the file name captured for downstream processing.
variable name that will be injected by the processing platform for job consumption.
* The Files object MUST have a member `mediaType`. The member's value MUST indicate the IANA Media type for
the file being captured by OutputData.
* The Files object MUST have a member `pattern`. The member's value MUST indicate a standard glob pattern for the
capture of files.
* The Files object MAY have a member `count`. The member's value MUST be a string that accepts 2 possibilities:
positive numeric values or a `\*`. Numeric values indicate an explicit match expected for `pattern` while `*` indicates
matching with no upper bound.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value is `true`.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string indicating the key the processing
system will place the JSON member value in for downstream use. When `key` member is omitted, it must be a case-sensitive
match of the member key in result manifest.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate the JSON schema type of
the member being captured from the result manifest.
* The JSON object MAY have a member `key`. The member's value MUST be a string and indicate the case-sensitive result
manifest member to capture. If omitted, the result member key is assumed to be a case-sensitive match for the above
defined `name` member.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippets provides quick reference to the use of OutputData object:

[source,javascript]
.Result Manifest
----
{
    "cellCount": 256,
    ...
}
----

[source,javascript]
.Seed Manifest - OutputData object
----
"outputData": {
    "files": [ // <1>
        {
            "name": "OUTPUT_TIFFS", // <2>
            "mediaType": "image/tiff", // <3>
            "pattern": "outfile*.tif", // <4>
            "count": "2", // <5>
            "required": true // <6>
        },
        ...
    ],
    "json": [ // <7>
        {
            "name": "CELL_COUNT", // <8>
            "type": "integer", // <9>
            "key": "cellCount" // <10>
        },
        ...
    ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing output identifier.
<3> Required string containing IANA Media type of file.
<4> Required string containing glob expression for file capture. Processing system is expected to
capture output relative to JOB_OUTPUT_DIR.
<5> Optional string containing either a numeric count or `*` for unbounded output. Default value
is `1`.
<6> Optional boolean indicating whether processing system should assume failure if output data is missing. Default value
is true.
<7> Optional array containing elements defined by JSON Elements sub-section.
<8> Required string containing output identifier. MUST be used by processing framework to match member for capture from
result manifest in absence of `key` member.
<9> Required string containing JSON schema type of member extracted from result manifest.
<10> Optional string containing key of result manifest member for extraction. This allows mapping from a result manifest
member key that differs from the value of `name` member.

[[mounts-section, Mounts Object]]
====== Mounts Object
The Mounts object is the member responsible for indicating any additional directories that must be mounted into the
container for the Job to run. A mount directory is typically a shared file system directory that contains some set of
reference data that the Job requires.

* The Mounts object MUST have a member `name`. The member's value is a string that correlates mount references
 elsewhere in the Interface to an external mount configuration that specifies how the mount is provided.
* The Mounts object MUST have a member `path`. The member's value is an absolute file system path specifying where in
 the container the Job expects the shared directory to be mounted.
* The Settings object MAY have a member `mode`. The member's value is a string that either specifies "ro" for read-only
 access to the directory or "rw" for read-write access. Default value is "ro".

The following annotated snippet provides quick reference to the use of the Mounts object:

[source,javascript]
----
[
    {
        "name": "MOUNT1", // <1>
        "path": "/the/container/path", // <2>
        "mode": "ro" // <3>
    },
    ...
]
----
<1> Required string containing the name to be used to lookup uses in the Interface.
<2> Required string indicating the absolute file system path where the directory should be mounted.
<3> Optional string indicating whether the directory should be mounted in read-only ("ro") or read-write ("rw") mode.

[[settings-section, Settings Object]]
====== Settings Object
The Settings object is the member responsible for indicating all content not related to data that is needed for the
Seed job to run. These will be exposed as environment variables at run time. Most commonly, Settings will be used for
environment specific configuration or external credentials.

While it is _highly_ advised that Seed jobs SHOULD limit input / output to the provided constructs (`inputData` /
`outputData`), there are justified use cases for violating this encapsulation. If database ingestion or downstream
 messaging are necessary, this is a reasonable mechanism to accomplish that.

* The Settings object MUST have a member `name`. The member's value is a string that indicates the case-sensitive
environment variable to be injected at run time.
* The Settings object MAY have a member `secret`. The member's value is a boolean that indicates whether the value
 associated with the named setting is secret and stored as a secure string.

The following annotated snippet provides quick reference to the use of the Settings object:

[source,javascript]
----
[
    {
        "name": "SETTING1", // <1>
        "secret": true // <2>
    },
    ...
]
----
<1> Required string containing the environment variable name to be injected at run time.
<2> Optional boolean indicating whether the setting value is sensitive and stored as a secret.

[[errormapping-section, ErrorMapping Objects]]
===== ErrorMapping Objects
The ErrorMapping objects allow for job developers to map arbitrary exit codes to meaningful textual descriptions. This
is useful in passing information to the processing system to differentiate between data and algorithm errors.

* The ErrorMapping object MUST have a member `code`. The member's value MUST be an integer indicating the exit code of
the executing job process.
* The ErrorMapping object MUST have a member `title`. The member's value MUST be a string indicating the short
descriptive title of the error.
* The ErrorMapping object MAY have a member `description`. The member's value MUST be a string indicating the complete
error description and possible causes.
* The ErrorMapping object MAY have a member `category`. If omitted, the default value is `algorithm`. The member's value
MUST be a string containing one of the following values: `algorithm`, `data` or `system`.

The following annotated snippet provides quick reference to the use of ErrorMapping objects:

[source,javascript]
----
[
    {
        "code": 1, // <1>
        "title": "Error Name", // <2>
        "description": "Error Description", // <3>
        "category": "system" // <4>
    },
    ...
]
----
<1> Required integer indicating job process exit code.
<2> Required string containing human-friendly short name of error.
<3> Optional string containing complete error code description.
<4> Optional string containing the error type. This value MUST be either: `algorithm`, `data` or `system`. The default
value is `algorithm`.
