
=== Implementing
A few requirements must be satisfied when implementing a system capable of executing Seed standardized images. The
following sections detail behavior that is expected of the execution framework, but these details are important for
algorithm developers to understand what execution context they are provided.

[[environment-variables, Environment Variables]]
==== Environment Variables
Environment variable injection MUST be performed as it is the primary means of providing the context required by the
defined interface of a Seed job. These environment variables MAY be consumed by a job directly or shell variable
expansion MAY be leveraged in the `interface.cmd` member. Implementing frameworks MAY perform variable expansion, but it
MUST follow Bash expansion conventions.

*NOTE*: Collisions between the reserved variables below and `interface.inputData.files`, `interface.inputData.json` and
`interface.settings` `name` member values MUST NOT occur.

The following minimum variables MUST be provided:

* JOB_OUTPUT_DIR: Absolute path where all output products MUST be placed by job for Seed executor capture.
* ALLOCATED_CPUS: Value of `cpus` member.
* ALLOCATED_MEM: Value of `mem` member.
* ALLOCATED_SHARED_MEM: Value of `sharedMem` member.
* ALLOCATED_STORAGE: Value of `storage` member.
* All `name` member values of `interface.inputData.files` elements MUST map to environment variables. Case MUST map
exactly from `name` value. Processing framework's MUST ensure data is mounted and provide a container resolvable
absolute path. _Injection behavior is dependent on the boolean value of `multiple` member._ When `multiple` is `true`
the injected environment variable MUST be an absolute path to a _directory_ with all files immediately beneath it. When
`multiple` is `false` it MUST be an absolute path to the single _file_ provided. This environment variable MUST be left
unset if member `required` is false and the input is not present.
* All `name` member values of `interface.inputData.json` elements MUST map to environment variables. Case MUST map
exactly from `name` value and `array`, `object` and `string` JSON types MUST be injected string encoded. This
environment variable MUST be left unset if `required` is false and the input is not present.
* All `name` member values of `interface.settings` elements MUST map to environment variables. Case MUST map
exactly from `name` value.

Supporting complex variable expansion where jobs require parameters associated with a switch can be accomplished with
use of Bash. Taking the example of an optional `inputData.files` element, the following `cmd` value will expand with
a preceding switch only when the input is available:

`${MY_INPUT/#/-d }`

This will expand to `-d ${MY_INPUT}` only when `MY_INPUT` is set, otherwise the entire expression will be omitted. It
is important to note this is specifically a Bash shell feature and is not present with competing Linux shells.

[[output-data-permissions, Output Data Permissions]]
==== Output Data Permissions
All output data generated by a Seed compliant algorithm MUST be placed within the location identified by JOB_OUTPUT_DIR
environment variable. This location SHALL be made available with permissions to be writable to the algorithm by the
execution framework. Algorithm developers MUST ensure any `interface.outputData.files` member elements, as well as the
optional `results_manifest.json` file, are marked with read permissions at minimum. This MAY be done with the following
sample command: `chmod +x yourfile.txt`

[[extended-file-metadata, Extended File Metadata]]
==== Extended File Metadata
There is often a need by the processing system to capture additional job extracted metadata on output files. The Seed
standard allows for this through the use of side-car files. The side-car files must be named exactly as the file they
describe, with the addition of the `.metadata.json` extension to the original file name (extension included). The file
must be formatted according to the <<seed-metadata-schema,Seed Metadata Schema>>. This allows for both
spatial and temporal metadata to be specified.

The following snippet demonstrates the optional values that may be specified:

[source,javascript]
.Metadata JSON
----
{
    "seedVersion": "0.0.5", <1>
    "geometry": { <2>
        "type": "Polygon",
	    "coordinates": [
	        [ [ 100.0, 0.0 ], [ 101.0, 0.0 ], [ 101.0, 1.0 ], [ 100.0, 1.0 ], [ 100.0, 0.0 ] ]
        ]
    },
    "time": { <3>
        "start": "2016-08-06T00:00:00.000Z", <4>
        "end": "2016-08-06T00:00:00.000Z" <5>
    }
}
----
<1> Required string indicating the Seed standard it complies with.
<2> Optional GeoJSON Geometry object defining spatial extent of file.
<3> Optional Time object defining temporal extent of file.
<4> Required string containing an ISO 8601 date indicating the start temporal extent of file. String must include full
time down to minute precision.
<5> Required string containing an ISO 8601 date indicating the end temporal extent of file. String must include full
time down to minute precision. If the data is a single point-in-time the end date should match the start date.

=== Examples
The Seed standard is intended to support both simple and complex job packaging. To that end the standard allows for
sensible defaults to take the place of a fully specified manifest. The following examples identify both a minimal
Seed use and a more realistic, fully exercised standard.

==== Random Number Generator Job
Minimal manifest demonstrating the simplest possible Seed definition.
----
include::../examples/random-number/seed.manifest.json[]
----

Serialized as a label in a Dockerfile snippet:
----
include::../examples/random-number/Dockerfile[]
----

==== Image Watermark Job
Image watermark job taking a single image and returning with watermark applied using Seed definition.
----
include::../examples/watermark/seed.manifest.json[]
----

Serialized as a label in a Dockerfile snippet:
----
include::../examples/watermark/Dockerfile[]
----
