
=== Implementing
A few requirements must be satisfied when an implementer† is building a system capable of executing Seed standardized
images. The following sections detail behavior that is expected of the executor†, but these details are also important
for developers† to understand what execution context they are provided.

[[environment-variables, Environment Variables]]
==== Environment Variables
Environment variable injection MUST be performed as it is the primary means of providing the context required by the
defined interface of a Seed job. These environment variables MAY be consumed by a job directly or shell variable
expansion MAY be leveraged in the `interface.command` member. Implementing frameworks MAY perform variable expansion,
but it MUST follow Bash expansion conventions.

[[variable-normalization, Normalization]]
===== Normalization
All environment variables injected MUST be normalized to remove any special characters. The majority of environment
variable injection is dynamic and tied to `name` member values. These values MUST be sanitized based on the following
rules:

* Only upper-case alphabetic and underscore characters are permitted unaltered.
* All lower-case alphabetic characters MUST be capitalized.
* All dash characters MUST be replaced with underscores.

[[variable-injection, Injection]]
===== Injection
WARNING: Collisions between the reserved variables below and `interface.inputs.files`, `interface.inputs.json` and
`interface.settings` `name` member values MUST NOT occur.

The following variables MUST be provided:

* OUTPUT_DIR: Absolute path where all output products MUST be placed by job for Seed executor† capture.
* All `name` member values of `resources.scalar` elements MUST map to environment variables. This SHALL be done by
<<variable-normalization,normalizing>> all `name` values and prefixing with `ALLOCATED_`. For a `my-demo-resourceNew`
with a value of `5.0`, an environment variable `ALLOCATED_MY_DEMO_RESOURCENEW` SHALL be set to `5.0` at run time. For a
resource with an `inputMultiplier` value the environment variable must include the final computed _output_ resource
allocation as defined in the `scalar` element under <<resources-section,Resources object>>. It SHOULD be clarified that
the allocated value computed using an `inputMultiplier` value MUST NOT include the size of input files - only the
additional space needed for output files during execution.
* All `name` member values of `interface.inputs.files` elements MUST map to environment variables. Variable names
must follow <<variable-normalization,normalization rules>>. _Executor's_ MUST ensure data is mounted and
provide a container resolvable absolute path. _Injection behavior is dependent on the boolean value of `multiple`
member._ When `multiple` is `true` the injected environment variable MUST be an absolute path to a _directory_ with all
files immediately beneath it. When `multiple` is `false` it MUST be an absolute path to the single _file_ provided. This
environment variable MUST be left unset if member `required` is false and the input is not present.
* All `name` member values of `interface.inputs.json` elements MUST map to environment variables. Variable names
must follow <<variable-normalization,normalization rules>> and `array`, `object` and `string` JSON types MUST be
injected string encoded. This environment variable MUST be left unset if `required` is false and the input is not
present.
* All `name` member values of `interface.settings` elements MUST map to environment variables. Variable names
must follow <<variable-normalization,normalization rules>>.

Supporting complex variable expansion where jobs require parameters associated with a switch can be accomplished with
use of Bash. Taking the example of an optional `inputs.files` element, the following `command` value will expand with
a preceding switch only when the input is available:

`${MY_INPUT/#/-d }`

This will expand to `-d ${MY_INPUT}` only when `MY_INPUT` is set, otherwise the entire expression will be omitted. It
is important to note this is specifically a Bash shell feature and is not present with competing Linux shells.

[[output-data-permissions, Output Data Permissions]]
==== Output Data Permissions
All output data generated by a Seed compliant job MUST be placed within the location identified by OUTPUT_DIR
environment variable. This location MUST be made available by the executor† so that the job is given full write
access. Developers MUST ensure any files captured by `interface.outputs.files` member element `pattern` values, as well
as the optional `seed.outputs.json` file, are marked with read permissions at minimum. This MAY be done with the
following sample command: `chmod +r yourfile.txt`

[[extended-file-metadata, Extended File Metadata]]
==== Extended File Metadata
There is often a need by the processing system to capture additional job extracted metadata on output files. The Seed
standard allows for this through the use of side-car files. The side-car files must be named exactly as the file they
describe, with the addition of the `.metadata.json` extension to the original file name (extension included). The file
must be formatted according to the <<seed-metadata-schema,Seed Metadata Schema>>. This allows for both
spatial and temporal metadata to be specified.

The following snippet demonstrates the optional values that may be specified:

[source,javascript]
.Metadata JSON
----
{
    "seedVersion": "0.1.0", <1>
    "geometry": { <2>
        "type": "Polygon",
	    "coordinates": [
	        [ [ 100.0, 0.0 ], [ 101.0, 0.0 ], [ 101.0, 1.0 ], [ 100.0, 1.0 ], [ 100.0, 0.0 ] ]
        ]
    },
    "time": { <3>
        "start": "2016-08-06T00:00:00.000Z", <4>
        "end": "2016-08-06T00:00:00.000Z" <5>
    }
}
----
<1> Required string indicating the Seed standard it complies with.
<2> Optional GeoJSON Geometry object defining spatial extent of file.
<3> Optional Time object defining temporal extent of file.
<4> Required string containing an ISO 8601 date indicating the start temporal extent of file. String must include full
time down to minute precision.
<5> Required string containing an ISO 8601 date indicating the end temporal extent of file. String must include full
time down to minute precision. If the data is a single point-in-time the end date should match the start date.

[[resource-defaults, Resource Defaults]]
==== Resource Defaults
At a minimum, the executor† MUST provide at least the resources indicated by a Seed manifest at run time. If the
resource requirement specified by the manifest is below the minimum amount allowed by the executor† it MAY increase the
requirement to that value. Developers† SHOULD specify the `cpu`, `mem` and `disk` requirements of their Seed job, but
if these are not set, the executor† is free to allocate minimal defaults.

For the `sharedMem` reserved resource, the executor† SHOULD make use of the Docker run argument `shm-size` to provide
the requested resource.

When resources are indicated by a Seed manifest that are not recognized by an executor†, the job SHOULD not be run.

=== Examples
The Seed standard is intended to support both simple and complex job packaging. To that end the standard allows for
sensible defaults to take the place of a fully specified manifest. The following examples identify both a minimal
Seed use and a more realistic, fully exercised standard.

==== Random Number Generator Job
Minimal manifest demonstrating the simplest possible Seed definition.
----
include::../examples/random-number/seed.manifest.json[]
----

Serialized as a label in a Dockerfile snippet:
----
include::../examples/random-number/Dockerfile[]
----

==== Image Watermark Job
Image watermark job taking a single image and returning with watermark applied using Seed definition.
----
include::../examples/watermark/seed.manifest.json[]
----

Serialized as a label in a Dockerfile snippet:
----
include::../examples/watermark/Dockerfile[]
----
