The JobPack standard is intended to provide a complete definition of the runtime processing, memory and storage
requirements of one or more discrete units of work, in addition to the inputs, outputs and potential errors produced.
Completeness is fundamental but the standard accommodates both simple and complex jobs by defining a minimal subset of
REQUIRED properties. The following sections detail every possible REQUIRED and OPTIONAL manifest property in both root
and child objects.

A complete JobPack object contained within a com.jobpack.manifest label is always a serialized object (in JSON terms).
In JobPack, an object consists of a collection of name/value pairs -- also called members. For each member, the name is
always a string. Member values are either a string, number, object, array or one of the literals: true, false, and null.
An array consists of elements where each element is a value as described above.

[[jobpack-section, JobPack Object]]
=== JobPack Object
The JobPack object is the root JSON object that MUST be placed within a com.jobpack.manifest Docker image label. At a
minimum this object MUST define the `manifestVersion` and `jobs` names.

* The JobPack object MUST have a member with the name `manifestVersion`. The member's value MUST be a string that
conforms to the SemVer standard.
* The JobPack object MUST have a member with the name `jobs`. The member's value is an array of `Job` objects and MUST
contain at least 1 element. There is no other standard restriction on the array size.
* The JobPack object MAY have any number of additional members.

----
{
  "manifestVersion": "0.0.1",
  "jobs": [...]
}
----

[[job-section, Job Objects]]
==== Job Objects
The Job object is the core member for describing a single unit of work and the resources it requires.

* The Job object MUST have a member with the name `name`. The member's value MUST be a string of only lowercase
alpha-numeric, dash or underscore characters (defined by the regex `[a-z0-9_-]+`).
* The Job object MUST have a member with the name `version`. The member's value MUST be a string that conforms to the
SemVer standard.
* The Job object MUST have a member with the name `title`. The member's value MUST be a string and SHOULD contain a
short descriptive title of the job.
* The Job object MUST have a member with the name `description`. The member's value MUST be a string and SHOULD contain
a full job abstract.
* The Job object MUST have a member with the name `authorName`. The member's value MUST be a string and SHOULD contain
the authoring individual or organization.
* The Job object MAY have a member with the name `authorUrl`. The member's value MUST be a string and SHOULD contain a
publicly accessible URL with further job detail.
* The Job object MUST have a member with the name `timeout`. This member's values MUST be a integer indicating a timeout
period measured in seconds. Consuming systems MUST honor this value as a hard limit on job execution time.
* The Job object MUST have a member with the name `cpus`. This member's value MUST be a number indicating the whole or
fractional CPUs allocated for the job.
* The Job object MUST have a member with the name `mem`. This member's value MUST be a number indicating the memory
requirement in Mebibytes (MiB) for the job. Fractional MiB values MAY be used to indicate allocations below 1 MiB.
* The Job object MAY have a member with the name `storage`. This member's value MUST be a number indicating the runtime
ephemeral storage requirements in Mebibytes (MiB) of the job. If omitted, the default of 0.0 may be assumed.
* The Job object MUST have a member with the name `interface`. This member's value MUST be an object as defined in
[[interface-section]]
`Interface`.
* The Job object MAY have a member with the name `errorMapping`. This member's value MUST be an array containing
elements defined in [[errormapping-section]]

The following annotated snippet provides quick reference to the use of Job object:

----
{
  "name": "my-algorithm", <1>
  "version": "1.0.0", <2>
  "title": "My first algorithm", <3>
  "description": "Reads an HDF5 file and outputs two TIFF images, a CSV and manifest containing cell_count", <4>
  "authorName": "John Doe", <5>
  "authorUrl": "http://www.example.com", <6>
  "timeout": 3600, <7>
  "cpus": 10.0, <8>
  "mem": 10240.0, <9>
  "storage": 0.0, <10>
  "interface": { ...  }, <11>
  "errorMapping": [ ... ] <12>
}
----
<1> Required string containing job identifier. Limited to regex `[a-z0-9_-]+`. `name` and `version` members combined should be unique
system-wide.
<2> Required string containing job version identifier in SemVer format. `name` and `version` members combined should be unique system-wide.
<3> Required string containing short job title.
<4> Required string containing job abstract. Inline markup should be avoided, but not prohibited.
<5> Required string containing job author name or organization.
<6> Optional string containing URL to job website.
<7> Required integer containing job timeout value in seconds.
<8> Required number containing CPU needs of job. Whole or fractional values allowed.
<9> Required number containing memory needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<10> Optional storage needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<11> Required [[interface-section]].
<12> Optional array of [[errormapping-section]].

[[interface-section, Interface Object]]
===== Interface Object
The Interface object is the primary member that describes the actual executable entrypoint, as well as inputs and
outputs defined for a job.

* The Interface object MUST have a member with the name `cmd`. The member's value MUST be a string specifying the
absolute path to the job executable within the Docker image.
* The Interface object MUST have a member with the name `args`. The member's value MUST be a string specifying the
complete parameter string passed to the executable defined in `cmd` member. Based on the Linux shell, shell escaping
of special characters MAY be required.
* The Interface object MUST have a member with the name `inputData`. The member's value is an array of `InputData`
objects (see [[inputdata-section]]) and MUST contain at least 1 element. There is no other standard restriction on the
array size.
* The Interface object MUST have a member with the name `outputData`. The member's value is an array of `OutputData`
objects (see [[inputdata-section]]) and MUST contain at least 1 element. There is no other standard restriction on the
array size.

----
{
  "cmd": "/app/job.sh",
  "args": "${INPUT_FILE} ${JOB_OUTPUT_DIR}",
  "inputData": [ { "name": "INPUT_FILE", ... }, ... ],
  "outputData": [ ... ]
}
----

[[inputdata-section, InputData Objects]]
====== InputData Objects
The InputData object is the member responsible for indicating all mutable content available to the JobPack image at
runtime.

* The InputData object MUST have a member `name`. The member's value MUST be a string indicating the environment
variable name that will be injected by the processing platform for job consumption.
* The InputData object MUST have a member `type`. The member's value MUST be a string containing either `file` or `json`
as the value. This value SHALL determine whether the value is directly injected or a reference to a file is given.
* The InputData object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value MAY always be expected. If omitted, the default value MUST be treated as true.
* The InputData object MUST have a member `content`. The member's value MUST be an object containing at minimum a member
`mediaType` with a value of string elements for `type` of `file` or a member of `type` when `type` is `json`. These
elements MUST be used by the processing system to validate file input.

The following annotated snippet provides quick reference to the use of InputData Objects:

----
[
  {
    "name": "INPUT_FILE", <1>
    "type": "file", <2>
    "required": true, <3>
    "content": {
      "mediaType": [ "image/x-hdf5-image" ] <4>
    }
  },
  {
    "name": "INPUT_STRING",
    "type": "json", <5>
    "required": false,
    "content": {
      "type": "string" <6>
    }
  }
]
----
<1> Required string containing name used to inject data via environment variables.
<2> Required string containing type differentiation between `file` and `json`. For member `type` set to `file` content
member object must contain a `mediaType` member identifying the accepted MIME types.
<3> Optional boolean indicating whether this job can be successfully executed without this particular value or file.
Default is `true`.
<4> Required array containing a list of accepted MIME types for `file` input.
<5> Required string containing type differentiation between `file` and `json`. For member `type` set to `json` content
member object must contain a `type` member identifying a valid JSON schema type.
<6> Required string containing a valid JSON schema type for `json` input.

[[outputdata-section, OutputData Objects]]
====== OutputData Objects


[[errormapping-section, ErrorMapping Objects]]
===== ErrorMapping Objects