The Seed standard is intended to provide a complete definition of the runtime processing, memory and storage
requirements of one or more discrete units of work, in addition to the inputs, outputs and potential errors produced.
Completeness is fundamental but the standard accommodates both simple and complex jobs by defining a minimal subset of
REQUIRED properties. The following sections detail every possible REQUIRED and OPTIONAL manifest property in both root
and child objects.

A complete Seed object contained within a com.ngageoint.seed.manifest label is always a string-escaped serialized
object. In Seed, an object consists of a collection of name/value pairs -- also called members. For each member, the
name is always a string. Member values are either a string, number, object, array or one of the literals: true, false,
and null. An array consists of elements where each element is a value as described above.

[[seed-section, Seed Object]]
=== Seed Object
The Seed object is the root JSON object that MUST be placed within a com.ngageoint.seed.manifest Docker image label.
At a minimum this object MUST define the `manifestVersion` and `jobs` names.

* The Seed object MUST have a member with the name `manifestVersion`. The member's value MUST be a string that
conforms to the SemVer standard.
* The Seed object MUST have a member with the name `jobs`. The member's value is an array of `Job` objects and MUST
contain at least 1 element. There is no other standard restriction on the array size.
* The Seed object MAY have any number of additional members.

[source,javascript]
----
{
  "manifestVersion": "0.0.1",
  "jobs": [ ... ]
}
----

[[job-section, Job Objects]]
==== Job Objects
The Job object is the core member for describing a single unit of work and the resources it requires.

* The Job object MUST have a member with the name `name`. The member's value MUST be a string of only lowercase
alpha-numeric, dash or underscore characters (defined by the regex `[a-z0-9_-]+`).
* The Job object MUST have a member with the name `version`. The member's value MUST be a string that conforms to the
SemVer standard.
* The Job object MUST have a member with the name `title`. The member's value MUST be a string and SHOULD contain a
short descriptive title of the job.
* The Job object MUST have a member with the name `description`. The member's value MUST be a string and SHOULD contain
a full job abstract.
* The Job object MAY have a member with the name `tag`. The member's value MUST be an array of strings and MAY contain
any number of elements.
* The Job object MUST have a member with the name `authorName`. The member's value MUST be a string and SHOULD contain
the authoring individual or organization.
* The Job object MAY have a member with the name `authorEmail`. The member's value MUST be a string and SHOULD contain
the authoring email address.
* The Job object MAY have a member with the name `authorUrl`. The member's value MUST be a string and SHOULD contain a
publicly accessible URL with further job detail.
* The Job object MUST have a member with the name `timeout`. This member's values MUST be a integer indicating a timeout
period measured in seconds. Consuming systems MUST honor this value as a hard limit on job execution time.
* The Job object MUST have a member with the name `cpus`. This member's value MUST be a number indicating the whole or
fractional CPUs allocated for the job.
* The Job object MUST have a member with the name `mem`. This member's value MUST be a number indicating the memory
requirement in Mebibytes (MiB) for the job. Fractional MiB values MAY be used to indicate allocations below 1 MiB.
* The Job object MAY have a member with the name `storage`. This member's value MUST be a number indicating the runtime
ephemeral storage requirements in Mebibytes (MiB) of the job. If omitted, the default of 0.0 may be assumed.
* The Job object MUST have a member with the name `interface`. This member's value MUST be an object as defined in
<<interface-section>>.
* The Job object MAY have a member with the name `errorMapping`. This member's value MUST be an array containing
elements defined in <<errormapping-section>>
* The Job object MAY have any number of additional members.

The following annotated snippet provides quick reference to the use of Job object:

[source,javascript]
----
{
  "name": "my-algorithm", // <1>
  "version": "1.0.0", // <2>
  "title": "My first algorithm", // <3>
  "description": "Reads an HDF5 file and outputs two TIFF images, a CSV and manifest containing cell_count", // <4>
  "authorName": "John Doe", // <5>
  "authorEmail": "jdoe@example.com", <6>
  "authorUrl": "http://www.example.com", // <7>
  "timeout": 3600,// <8>
  "cpus": 10.0, // <9>
  "mem": 10240.0, // <10>
  "storage": 0.0, // <11>
  "interface": { ... }, // <12>
  "errorMapping": [ ... ] // <13>
}
----
<1> Required string containing job identifier. Limited to regex `[a-z0-9_-]+`. `name` and `version` members combined
should be unique system-wide.
<2> Required string containing job version identifier in SemVer format. `name` and `version` members combined should be
unique system-wide.
<3> Required string containing short job title.
<4> Required string containing job abstract. Inline markup should be avoided, but not prohibited.
<5> Required string containing job author name or organization.
<6> Optional string containing job author email.
<7> Optional string containing URL to job website.
<8> Required integer containing job timeout value in seconds.
<8> Required number containing CPU needs of job. Whole or fractional values allowed.
<10> Required number containing memory needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<11> Optional number containing storage needs of job in Mebibytes (MiB). Whole or fractional values allowed.
<12> Required <<interface-section>>.
<13> Optional array of <<errormapping-section>>.

[[interface-section, Interface Object]]
===== Interface Object
The Interface object is the primary member that describes the actual executable entrypoint, environment variables,
settings, inputs and outputs defined for a job.

* The Interface object MUST have a member with the name `cmd`. The member's value MUST be a string specifying the
absolute path to the job executable within the Docker image.
* The Interface object MAY have a member with the name `args`. The member's value MUST be a string specifying the
complete parameter string passed to the executable defined in `cmd` member. Based on the Linux shell, shell escaping
of special characters MAY be required.
* The Interface object MAY have a member with the name `inputData`. The member's value is an array of `InputData`
objects (see <<inputdata-section>>) and MAY contain any number of elements.
* The Interface object MAY have a member with the name `outputData`. The member's value is an array of `OutputData`
objects (see <<outputdata-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.
* The Interface object MAY have a member with the name `settings`. The member's value is an array of `Settings`
objects (see <<settings-section>>) and MAY contain any number of elements. There is no other standard restriction on
the array size.
* The Interface object MAY have a member with the name `envVars`. The member's value is an array of
`Environment Variables` objects (see <<envvars-section>>) and MAY contain any number of elements. There is no other
standard restriction on the array size.

The following annotated snippet provides quick reference to the use of Interface object:

[source,javascript]
----
{
  "cmd": "/app/job.sh", // <1>
  "args": "${INPUT_FILE} ${JOB_OUTPUT_DIR}", // <2>
  "inputData": { "files": [ { "name": "INPUT_FILE", ... }, ... ] }, // <3>
  "outputData": { ... }, // <4>
  "envVars": { ... }, // <5>
  "settings": { ... } // <6>
}
----
<1> Required string indicating the job executable. It should be an absolute path for clarity.
<2> Optional string indicating the job arguments. Shell expansion may be used to inject existing environment variables
and executable arguments. Linux shell escaping may be needed in the case of special characters.
<3> Optional <<inputdata-section>>. This is the means to inject external data into the job container.
<4> Optional <<outputdata-section>>. This is the means to capture results from the job container.
<5> Optional <<envvars-section>>. This is a means to set environment variables before a job is run.
<6> Optional <<settings-section>>. This defines any settings that are used by the args or envVars.

[[inputdata-section, InputData Object]]
====== InputData Object
The InputData object is the member responsible for indicating all mutable content available to the Seed image at
runtime.

* The InputData object MAY have a member `files`. The member's value is an array of objects defined in Files Elements
sub-section.
* The InputData object MAY have a member `json`. The member's value is an array of objects defined in JSON Elements
sub-section.

.Files Elements
* The Files object MUST have a member `name`. The member's value MUST be a string indicating the environment
variable name that will be injected by the processing platform for job consumption.
* The Files object MUST have a member `mediaType`. The member's value MUST indicate the IANA Media type for
the file being captured by OutputData.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string indicating the environment
variable name that will be injected by the processing platform for job consumption.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate a valid JSON schema type.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippet provides quick reference to the use of InputData object:

[source,javascript]
----
{
  "files": [ // <1>
    {
      "name": "INPUT_FILE", // <2>
      "mediaType": [ "image/x-hdf5-image" ], // <3>
      "required": true // <4>
    }
  ]
  "json": [ // <5>
    {
      "name": "INPUT_STRING",
      "type": "string", // <6>
      "required": false // <7>
    }
  ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing name used to inject data via environment variables.
<3> Required array containing a list of accepted Media types.
<4> Optional boolean indicating whether job requires this particular file. Default is `true`.
<5> Optional array containing elements defined by JSON Elements sub-section.
<6> Required string containing a valid JSON schema type for input validation.
<7> Optional boolean indicating whether job requires this particular JSON input. Default is `true`.

[[outputdata-section, OutputData Object]]
====== OutputData Object
The OutputData object is the member responsible for indicating all output data and the means to capture that data
following the execution of a Seed image. Data can be captured in two different forms: directly as a file or
extracted JSON from a manifest. File type output is simply matched based on a standard glob pattern. JSON objects are
expected to be gathered from a results manifest that by Seed standard convention MUST be provided either on container
STDOUT or written at the root of the job output directory as `results_manifest.json`. The location of the job output
directory is REQUIRED to be passed into the container at job execution time.

* The OutputData object MAY have a member `files`. The member's value is an array of objects defined in Files Elements
sub-section.
* The OutputData object MAY have a member `json`. The member's value is an array of objects defined in JSON Elements
sub-section.

.Files Elements
* The Files object MUST have a member `name`. The member's value MUST be a string indicating the key the processing
system will place the file name captured for downstream processing.
variable name that will be injected by the processing platform for job consumption.
* The Files object MUST have a member `mediaType`. The member's value MUST indicate the IANA Media type for
the file being captured by OutputData.
* The Files object MUST have a member `pattern`. The member's value MUST indicate a standard glob pattern for the
capture of files.
* The Files object MAY have a member `count`. The member's value MUST be a string that accepts 2 possibilities:
positive numeric values or a `\*`. Numeric values indicate an explicit match expected for `pattern` while `*` indicates
matching with no upper bound.
* The Files object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value is `true`.

.JSON Elements
* The JSON object MUST have a member `name`. The member's value MUST be a string indicating the key the processing
system will place the JSON member value in for downstream use. When `key` member is omitted, it must be a case-sensitive
match of the member key in result manifest.
* The JSON object MUST have a member `type`. The member's value MUST be a string and indicate the JSON schema type of
the member being captured from the result manifest.
* The JSON object MAY have a member `key`. The member's value MUST be a string and indicate the case-sensitive result
manifest member to capture. If omitted, the result member key is assumed to be a case-sensitive match for the above
defined `name` member.
* The JSON object MAY have a member `required`. The member's value MUST be a boolean indicating whether this input
value SHOULD always be expected. If omitted, the default value MUST be treated as true.

The following annotated snippets provides quick reference to the use of OutputData object:

[source,javascript]
.Result Manifest
----
{
  "cellCount": 256,
  ...
}
----

[source,javascript]
.Seed Manifest - OutputData object
----
"outputData": {
  "files": [ // <1>
    {
	  "name": "OUTPUT_TIFFS", // <2>
	  "mediaType": "image/tiff", // <3>
	  "pattern": "outfile*.tif", // <4>
	  "count": "2", // <5>
	  "required": true // <6>
	}
  ],
  "json": [ // <7>
    {
      "name": "CELL_COUNT", // <8>
      "type": "integer", // <9>
      "key": "cellCount" // <10>
    }
  ]
}
----
<1> Optional array containing elements defined by Files Elements sub-section.
<2> Required string containing output identifier.
<3> Required string containing IANA Media type of file.
<4> Required string containing glob expression for file capture. Processing system is expected to
capture output relative to JOB_OUTPUT_DIR.
<5> Optional string containing either a numeric count or `\*` for unbounded output. Default value
is `1`.
<6> Optional boolean indicating whether processing system should assume failure if output data is missing. Default value
is true.
<7> Optional array containing elements defined by JSON Elements sub-section.
<8> Required string containing output identifier. MUST be used by processing framework to match member for capture from
result manifest in absence of `key` member.
<9> Required string containing JSON schema type of member extracted from result manifest.
<10> Optional string containing key of result manifest member for extraction. This allows mapping from a result manifest
member key that differs from the value of `name` member.

[[settings-section, Settings Object]]
====== Settings Object
The Settings object is the member responsible for indicating all content not related to data that is needed for the
Job to run.

* The Settings object MUST have a member `name`. The member's value is a string that correlates to referenced setting
injections elsewhere in the Interface.
* The Settings object MUST have a member `value`. The member's value is a string that indicates the desired value to
associate with the setting object.

The following annotated snippet provides quick reference to the use of the Settings object:

[source,javascript]
----
{
  "name": "SETTING1", // <1>
  "value": "5432" // <2>
}
----
<1> Required string containing the name to be used to lookup uses in the Interface.
<2> Required string indicating the value to associate with the setting name.

[[envvars-section, Environment Variables Object]]
====== Environment Variables Object
The Environment Variables object is the member responsible for defining any values that need to be set as environment
variables in the runtime that will be executing the job.

* The envVars object MAY have a member `name`. The member's value is a case-sensitive string defining the name of the
environment variable.
* The envVars object MAY have a member `value`. The member's value is a case-sensitive string defining the value of the
environment variable.

The following annotated snippet provides quick reference to the use of the envVars object:

[source,javascript]
----
{
  "name": "DB_PORT", // <1>
  "value": "${SETTING1}" // <2>
}
----
<1> Required string containing the name portion of a name/value environment variable pair.
<2> Required string containing the value portion of a name/value environment variable pair.


[[errormapping-section, ErrorMapping Objects]]
===== ErrorMapping Objects
The ErrorMapping objects allow for job developers to map arbitrary exit codes to meaningful textual descriptions. This
is useful in passing information to the processing system to differentiate between data and algorithm errors.

* The ErrorMapping object MUST have a member `code`. The member's value MUST be an integer indicating the exit code of
the executing job process.
* The ErrorMapping object MUST have a member `title`. The member's value MUST be a string indicating the short
descriptive title of the error.
* The ErrorMapping object MAY have a member `description`. The member's value MUST be a string indicating the complete
error description and possible causes.
* The ErrorMapping object MAY have a member `category`. If omitted, the default value is `algorithm`. The member's value
MUST be a string containing one of the following values: `algorithm`, `data` or `system`.

The following annotated snippet provides quick reference to the use of ErrorMapping objects:

[source,javascript]
----
[
  {
    "code": 1, // <1>
    "title": "Error Name", // <2>
    "description": "Error Description", // <3>
    "category": "system" // <4>
  }
]
----
<1> Required integer indicating job process exit code.
<2> Required string containing human-friendly short name of error.
<3> Optional string containing complete error code description.
<4> Optional string containing the error type. This value MUST be either: `algorithm`, `data` or `system`. The default
value is `algorithm`.
