= Seed Standard Definition
Jonathan Meyer <jonathan.meyer@appliedis.com>; Mike Holt <mholt1@ball.com>; Derick Faller <dfaller@ball.com>; John Tobe <jtobe@ball.com>
vSEED_VERSION
:toc: left
:toclevels: 5
:sectlinks:
:sectnums:
:sectnumlevels: 5
:icons: font
:docinfo:

== Introduction

Seed is a general standard to aid in the discovery and consumption of a discrete unit of work contained within a Docker
image. While initially developed to support the http://ngageoint.github.io/scale/[Scale] data processing system with job
discovery, it is designed to be readily applied to other systems as well.

Seed compliant images must be named in a specific fashion due to the lack of label search capability on Docker Hub
and Registry services. The suffix `-seed` must be used when naming images to enable discovery, prior to Hub or
Registry push. This requirement will be deprecated as label search support is standardized across Docker registry
services. Use of the http://github.com/ngageoint/seed-cli[CLI] developed by the Seed team is highly recommended to speed
the development and packaging of jobs according to the Seed specification.

=== Format

The Docker image created must adhere to a specific naming convention. The standard requires specification of both an
job and a packaging version, tracking changes individually between the job logic and the packaging of it.
The following image naming template maps to members defined under the <<job-section>>:

----
<name>-<jobVersion>-seed:<packageVersion>
----

Dockerfile snippet containing required label for Seed compliance:

----
include::examples/complete/Dockerfile-snippet[]
----

The `com.ngageoint.seed.manifest` label contents must be serialized as a string-escaped JSON object. The following is a
complete example including required and optional keys:

----
include::examples/complete/seed.manifest.json[]
----

=== Definitions
* Seed specific terms defined in the <<Glossary>> supersede all following definitions. These terms can be found
_italicized_ throughout the specification.
* GeoJSON, and the terms Geometry and Polygon are defined in
https://www.ietf.org/id/draft-ietf-geojson-03.txt[IETF GeoJSON Draft-03]
* Internet Assigned Numbers Authority (IANA), and the terms Media Types and MIME Types are defined in
http://www.iana.org/assignments/media-types/media-types.xhtml[IETF RFC 6838]
* ISO 8601 and the specifics of the date format are defined in https://tools.ietf.org/html/rfc3339[IETF RFC 3339]
* JavaScript Object Notation (JSON), and the terms object, name, value, array, and number, are defined in
http://www.ietf.org/rfc/rfc4627.txt[IETF RFC 4627].
* Semantic Versioning (SemVer), and the terms major, minor, and patch version are defined at
http://semver.org/spec/v2.0.0.html
* The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in http://www.ietf.org/rfc/rfc2119.txt[IETF RFC 2119].

== Standard
include::sections/standard.adoc[]

== Usage
include::sections/usage.adoc[]

== Discovery
include::sections/discovery.adoc[]

== Glossary
The following terms are specific to Seed and are provided to clarify their meaning. They are marked with a dagger (†)
throughout the document.

|===
|Term |Description

|developer
|creator and packager of Seed compliant image

|executor
|process responsible for injecting run-time context (inputs, mounts and environment settings) and capturing all
resulting output (files, json).

|implementer
|developer of framework for discovering or running Seed compliant images - must provide executor

|regex
|short hand for "Regular Expression," a text string that defines a pattern to be applied to other strings. http://regexr.com/[More info]

|glob
|a string defining a pattern to be applied to files on *nix operating systems. http://man7.org/linux/man-pages/man7/glob.7.html[More info]
|===

== Schema

[[seed-manifest-schema, Seed Manifest]]
=== Seed Manifest
The following JSON Schema should be used to validate Seed manifests prior to label serialization into a Dockerfile
for publish. It may be downloaded here: link:schema/seed.manifest.schema.json[Seed Manifest Schema]

----
include::schema/seed.manifest.schema.json[]
----

[[seed-metadata-schema, Seed Metadata]]
=== Seed Metadata
The following JSON Schema should be used to validate the side-car metadata files generated alongside Seed job output
files. It may be downloaded here: link:schema/seed.metadata.schema.json[Seed Metadata Schema]

----
include::schema/seed.metadata.schema.json[]
----
